export const stylesCalendar = {
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 10,
  },
  activityItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 12,
    borderRadius: 8,
    marginVertical: 6,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  activityTextContainer: {
    flex: 1,
  },
  activityName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2d4150",
    marginBottom: 4,
  },
  activityTime: {
    fontSize: 14,
    color: "#555",
  },
  activityButtons: {
    flexDirection: "row",
    gap: 10,
  },
  editButton: {
    backgroundColor: "#007BFF",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButton: {
    backgroundColor: "#DC3545",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  activitiesContainer: {
    marginTop: 10,
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  activitiesTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2d4150",
    marginBottom: 10,
  },
  activitiesList: {
    maxHeight: 250,
  },
};
