export const stylesHorarios = {
    container: {
        flex: 1,
        backgroundColor: "#f8f9fa",
      },
      searchContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 8,
        margin: 10,
        paddingHorizontal: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
      },
      searchIcon: {
        marginRight: 8,
      },
      searchInput: {
        flex: 1,
        height: 46,
        fontSize: 16,
      },
      list: {
        padding: 10,
      },
      card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
      },
      cardHeader: {
        marginBottom: 12,
      },
      cardTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#333",
      },
      cardSubtitle: {
        fontSize: 14,
        color: "#666",
        marginTop: 4,
      },
      cardActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
      },
      viewButton: {
        backgroundColor: "#007BFF",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
        flexDirection: "row",
        alignItems: "center",
      },
      buttonText: {
        color: "#fff",
        marginLeft: 4,
        fontWeight: "500",
      },
      emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        padding: 40,
      },
      emptyText: {
        fontSize: 18,
        fontWeight: "600",
        color: "#555",
        marginTop: 12,
      },
      emptySubText: {
        fontSize: 14,
        color: "#888",
        marginTop: 8,
        textAlign: "center",
      },
      fab: {
        position: "absolute",
        bottom: 16,
        right: 16,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: "#007BFF",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 5,
      },
      modalContainer: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
      },
      modalContent: {
        backgroundColor: "#fff",
        marginHorizontal: 20,
        borderRadius: 12,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      modalTitle: {
        fontSize: 20,
        fontWeight: "600",
        marginBottom: 16,
        color: "#333",
        textAlign: "center",
      },
      inputLabel: {
        fontSize: 14,
        fontWeight: "500",
        color: "#555",
        marginBottom: 4,
      },
      textInput: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 6,
        padding: 10,
        fontSize: 16,
        marginBottom: 12,
      },
      pickerContainer: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 6,
        marginBottom: 12,
        overflow: "hidden",
      },
      picker: {
        height: 50,
        width: "100%",
      },
      timeContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
      },
      timeField: {
        width: "48%",
      },
      modalButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 16,
      },
      modalButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 6,
        alignItems: "center",
        justifyContent: "center",
        flex: 1,
        marginHorizontal: 5,
      },
      saveButton: {
        backgroundColor: "#007BFF",
      },
      saveButtonText: {
        color: "#fff",
        fontWeight: "600",
        fontSize: 16,
      },
      cancelButton: {
        backgroundColor: "#f2f2f2",
      },
      cancelButtonText: {
        color: "#666",
        fontWeight: "600",
        fontSize: 16,
      },
      scheduleContainer: {
        flex: 1,
      },
      scheduleHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 10,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
      },
      backButton: {
        padding: 5,
      },
      scheduleTitle: {
        fontSize: 18,
        fontWeight: "600",
        flex: 1,
        marginLeft: 10,
      },
      addButton: {
        padding: 5,
      },
      scheduleScrollContainer: {
        flex: 1,
      },
      scheduleTable: {
        margin: 10,
      },
      tableRow: {
        flexDirection: "row",
      },
      timeCell: {
        width: 80,
        height: 60,
        padding: 5,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#f8f9fa",
        borderWidth: 0.5,
        borderColor: "#ddd",
      },
      timeCellText: {
        fontSize: 12,
        color: "#666",
        textAlign: "center",
      },
      dayHeaderCell: {
        width: 120,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#007BFF",
        borderWidth: 0.5,
        borderColor: "#ddd",
      },
      dayHeaderText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#fff",
      },
      tableCell: {
        width: 120,
        height: 60,
        padding: 2,
        borderWidth: 0.5,
        borderColor: "#ddd",
        overflow: "hidden",
      },
      emptyCell: {
        flex: 1,
        backgroundColor: "#fff",
      },
      recesoCell: {
        flex: 1,
        backgroundColor: "#f0f0f0",
        justifyContent: "center",
        alignItems: "center",
      },
      recesoText: {
        fontSize: 12,
        color: "#888",
        fontWeight: "500",
      },
      classCell: {
        flex: 1,
        borderRadius: 4,
        padding: 4,
        justifyContent: "center",
        borderColor: "#ddd",
      },
      classCellTitle: {
        fontSize: 12,
        fontWeight: "600",
        color: "#1565C0",
      },
      classCellSubtitle: {
        fontSize: 10,
        color: "#5C6BC0",
      },
      classCellTime: {
        fontSize: 9,
        color: "#5C6BC0",
        marginTop: 2,
      },
      legendScrollContainer: {
        maxHeight: 200,
        backgroundColor: "#fff",
      },
      legendContainer: {
        padding: 10,
        borderTopWidth: 1,
        borderTopColor: "#eee",
      },
      legendTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 8,
        color: "#333",
      },
      legendItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        paddingBottom: 8,
        borderBottomWidth: 0.5,
        borderBottomColor: "#eee",
      },
      legendColor: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
      },
      legendInfo: {
        flex: 1,
      },
      legendText: {
        fontSize: 14,
        color: "#333",
      },
      legendSubtext: {
        fontSize: 12,
        color: "#666",
      },
      legendActions: {
        flexDirection: "row",
      },
      legendButton: {
        padding: 5,
        marginLeft: 5,
      },
}